import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { assertCanAccessArea, assertNationalAdmin, hasCompletedQualityChecks } from "../access";
import { archiveEmergencyNotice, assignAreaAdmin, createArea, createEmergencyNotice, createManagedContent, createManagedMeeting, findAreaAdminUserIds, findNationalAdminUserIds, getAreasByIds, getManagedContent, getManagedMeeting, getNotificationsForUser, getUserAreaIds, listAssignableUsers, listEmergencyNotices, listManagedContent, listManagedMeetings, notifyUsers, publishEmergencyNotice, removeManagedMeeting, reviewManagedMeeting, submitManagedContent, submitManagedMeeting, updateEmergencyNotice, updateManagedContent, updateManagedMeeting } from "../db";
import { adminProcedure, protectedProcedure, router } from "../_core/trpc";

const dayValues = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"] as const;
export const meetingInputSchema = z.object({ areaId: z.number().int().positive(), meetingName: z.string().trim().min(2).max(255), venueName: z.string().trim().max(255).optional(), streetAddress: z.string().trim().max(255).optional(), suburb: z.string().trim().max(160).optional(), city: z.string().trim().max(160).optional(), province: z.string().trim().max(120).optional(), latitude: z.number().min(-90).max(90).optional(), longitude: z.number().min(-180).max(180).optional(), daysOfWeek: z.array(z.enum(dayValues)).min(1), startTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), meetingType: z.string().trim().min(2).max(100), meetingFormat: z.enum(["in_person", "online", "hybrid"]), contactPerson: z.string().trim().max(160).optional(), phone: z.string().trim().max(64).optional(), specialNotes: z.string().trim().max(3000).optional(), onlineUrl: z.string().url().max(1024).optional(), geocodeFormattedAddress: z.string().trim().max(512).optional(), geocodePlaceId: z.string().trim().max(255).optional() });

async function assertMeetingScope(user: { id: number; role: "user" | "area_admin" | "admin" }, meetingId: number) { const meeting = await getManagedMeeting(meetingId); if (!meeting) throw new TRPCError({ code: "NOT_FOUND", message: "Meeting not found." }); const areaIds = await getUserAreaIds(user.id); assertCanAccessArea(user, areaIds, meeting.areaId); return meeting; }

export const adminRouter = router({
  scope: protectedProcedure.query(async ({ ctx }) => { const areaIds = await getUserAreaIds(ctx.user.id); return { role: ctx.user.role, areas: ctx.user.role === "admin" ? undefined : await getAreasByIds(areaIds) }; }),
  meetings: protectedProcedure.input(z.object({ status: z.enum(["draft", "submitted", "changes_requested", "published", "archived"]).optional() }).optional()).query(async ({ ctx, input }) => { const areaIds = await getUserAreaIds(ctx.user.id); if (ctx.user.role !== "admin" && ctx.user.role !== "area_admin") return []; return listManagedMeetings(areaIds, ctx.user.role === "admin", input?.status); }),
  createMeeting: protectedProcedure.input(meetingInputSchema).mutation(async ({ ctx, input }) => { const areaIds = await getUserAreaIds(ctx.user.id); assertCanAccessArea(ctx.user, areaIds, input.areaId); return createManagedMeeting(input, ctx.user.id); }),
  updateMeeting: protectedProcedure.input(z.object({ id: z.number().int().positive(), meeting: meetingInputSchema })).mutation(async ({ ctx, input }) => { const existing = await assertMeetingScope(ctx.user, input.id); if (existing.areaId !== input.meeting.areaId) throw new TRPCError({ code: "FORBIDDEN", message: "A meeting cannot be moved between areas in this workflow." }); return updateManagedMeeting(input.id, input.meeting, ctx.user.id); }),
  deleteMeeting: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const meeting = await assertMeetingScope(ctx.user, input.id); await removeManagedMeeting(input.id, ctx.user.id, meeting.areaId); return { success: true }; }),
  submitMeeting: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const meeting = await assertMeetingScope(ctx.user, input.id); if (meeting.meetingFormat !== "online" && (!meeting.latitude || !meeting.longitude || !meeting.geocodeFormattedAddress || !meeting.geocodePlaceId)) throw new TRPCError({ code: "BAD_REQUEST", message: "Validate the in-person address and save its coordinates before submitting this meeting for review." }); await submitManagedMeeting(meeting.id, ctx.user.id, meeting.areaId); await notifyUsers(await findNationalAdminUserIds(), { areaId: meeting.areaId, kind: "meeting_submitted", title: "Meeting submitted for review", body: `${meeting.meetingName} was submitted by an area administrator.`, entityType: "meeting", entityId: meeting.id }); return { success: true }; }),
  notifications: protectedProcedure.query(({ ctx }) => getNotificationsForUser(ctx.user.id)),
  reviewMeeting: adminProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["published", "changes_requested"]), addressVerified: z.boolean(), mapPinConfirmed: z.boolean(), spellingChecked: z.boolean(), contactConfirmed: z.boolean(), reviewNotes: z.string().trim().max(3000).optional() })).mutation(async ({ ctx, input }) => { const existing = await getManagedMeeting(input.id); if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "Meeting not found." }); if (input.status === "published") { if (!hasCompletedQualityChecks(input)) throw new TRPCError({ code: "BAD_REQUEST", message: "All four quality checks must be confirmed before publication." }); if (existing.meetingFormat !== "online" && (!existing.latitude || !existing.longitude)) throw new TRPCError({ code: "BAD_REQUEST", message: "An in-person or hybrid meeting needs validated GPS coordinates before publication." }); }
    const reviewed = await reviewManagedMeeting(input.id, ctx.user.id, input); if (input.status === "changes_requested") await notifyUsers(await findAreaAdminUserIds(existing.areaId), { areaId: existing.areaId, kind: "meeting_flagged", title: "Meeting requires review", body: `${existing.meetingName} was flagged by national review.${input.reviewNotes ? ` Note: ${input.reviewNotes}` : ""}`, entityType: "meeting", entityId: existing.id }); return reviewed; }),
  content: router({
    list: protectedProcedure.query(async ({ ctx }) => { const areaIds = await getUserAreaIds(ctx.user.id); if (ctx.user.role !== "admin" && ctx.user.role !== "area_admin") return []; return listManagedContent(areaIds, ctx.user.role === "admin"); }),
    create: protectedProcedure.input(z.object({ areaId: z.number().int().positive().optional(), slug: z.string().trim().regex(/^[a-z0-9-]+$/).max(180), title: z.string().trim().min(2).max(255), excerpt: z.string().trim().max(1000).optional(), body: z.string().trim().min(10).max(50000) })).mutation(async ({ ctx, input }) => { const areaIds = await getUserAreaIds(ctx.user.id); if (input.areaId) assertCanAccessArea(ctx.user, areaIds, input.areaId); if (!input.areaId && ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "Only a national administrator can create national content." }); return createManagedContent(input, ctx.user.id); }),
    update: protectedProcedure.input(z.object({ id: z.number().int().positive(), content: z.object({ slug: z.string().trim().regex(/^[a-z0-9-]+$/).max(180), title: z.string().trim().min(2).max(255), excerpt: z.string().trim().max(1000).optional(), body: z.string().trim().min(10).max(50000) }) })).mutation(async ({ ctx, input }) => { const existing = await getManagedContent(input.id); if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "Content not found." }); const areaIds = await getUserAreaIds(ctx.user.id); if (existing.areaId) assertCanAccessArea(ctx.user, areaIds, existing.areaId); else assertNationalAdmin(ctx.user); return updateManagedContent(input.id, { ...input.content, areaId: existing.areaId ?? undefined }, ctx.user.id); }),
    submit: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const existing = await getManagedContent(input.id); if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "Content not found." }); const areaIds = await getUserAreaIds(ctx.user.id); if (existing.areaId) assertCanAccessArea(ctx.user, areaIds, existing.areaId); else assertNationalAdmin(ctx.user); await submitManagedContent(input.id, ctx.user.id, existing.areaId); await notifyUsers(await findNationalAdminUserIds(), { areaId: existing.areaId ?? undefined, kind: "content_submitted", title: "Content submitted for review", body: `${existing.title} was submitted for national review.`, entityType: "content", entityId: existing.id }); return { success: true }; }),
  }),
  emergency: router({
    list: adminProcedure.query(async ({ ctx }) => { assertNationalAdmin(ctx.user); return listEmergencyNotices(); }),
    create: adminProcedure.input(z.object({ title: z.string().trim().min(3).max(255), message: z.string().trim().min(3).max(5000), severity: z.enum(["info", "urgent"]), startsAt: z.coerce.date(), endsAt: z.coerce.date().optional() })).mutation(async ({ ctx, input }) => { assertNationalAdmin(ctx.user); if (input.endsAt && input.endsAt <= input.startsAt) throw new TRPCError({ code: "BAD_REQUEST", message: "The end time must be after the start time." }); return createEmergencyNotice(input, ctx.user.id); }),
    update: adminProcedure.input(z.object({ id: z.number().int().positive(), title: z.string().trim().min(3).max(255), message: z.string().trim().min(3).max(5000), severity: z.enum(["info", "urgent"]), startsAt: z.coerce.date(), endsAt: z.coerce.date().optional() })).mutation(async ({ ctx, input }) => { assertNationalAdmin(ctx.user); if (input.endsAt && input.endsAt <= input.startsAt) throw new TRPCError({ code: "BAD_REQUEST", message: "The end time must be after the start time." }); return updateEmergencyNotice(input.id, { title: input.title, message: input.message, severity: input.severity, startsAt: input.startsAt, endsAt: input.endsAt }, ctx.user.id); }),
    publish: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertNationalAdmin(ctx.user); return publishEmergencyNotice(input.id, ctx.user.id); }),
    archive: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertNationalAdmin(ctx.user); await archiveEmergencyNotice(input.id, ctx.user.id); return { success: true }; }),
  }),
  national: router({
    listUsers: adminProcedure.query(async ({ ctx }) => { assertNationalAdmin(ctx.user); return listAssignableUsers(); }),
    createArea: adminProcedure.input(z.object({ name: z.string().trim().min(2).max(160), slug: z.string().trim().regex(/^[a-z0-9-]+$/).max(80), province: z.string().trim().max(120).optional() })).mutation(async ({ ctx, input }) => { assertNationalAdmin(ctx.user); return { id: await createArea(input) }; }),
    assignAreaAdmin: adminProcedure.input(z.object({ userId: z.number().int().positive(), areaId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertNationalAdmin(ctx.user); await assignAreaAdmin(input); return { success: true }; }),
  }),
});
