import { BookOpen, Download, ExternalLink, FileText, Library } from "lucide-react";
import { Link } from "wouter";
import PublicLayout from "@/components/PublicLayout";
import { literatureManifest, type LiteratureManifestItem } from "@/data/literatureManifest";

const officialCatalogue = "https://na.org/literature/recovery-literature-in-english-usa/";
const literatureDeployment = "literature-live-20260816-1140";
const grouped = literatureManifest.reduce<Record<string, LiteratureManifestItem[]>>((groups, item) => {
  (groups[item.category] ??= []).push(item);
  return groups;
}, {});
const categoryOrder = ["Recovery booklets", "Information pamphlets", "Group and service resources", "Service and meeting resources", "Policies and local resources", "Additional NA resources"];

function ResourceCard({ item }: { item: LiteratureManifestItem }) {
  return <Link href={`/literature/${item.slug}`} target="_blank" rel="noreferrer" className="group flex min-h-[184px] flex-col rounded-2xl border border-[#DDE6EB] bg-white p-5 shadow-[0_8px_24px_rgba(20,45,42,0.04)] transition hover:-translate-y-0.5 hover:border-[#085C84]/35 hover:shadow-[0_14px_30px_rgba(8,92,132,0.13)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#387CBB]"><div className="flex items-start justify-between gap-3"><span className="inline-flex rounded-full bg-[#EAF5EC] px-3 py-1 text-xs font-bold text-[#20752C]">PDF download</span><ExternalLink className="h-4 w-4 shrink-0 text-[#085C84]" aria-hidden="true" /></div><h3 className="mt-5 text-base font-bold leading-6 text-[#54595F]">{item.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-[#7A7A7A]">{item.description}</p><span className="mt-auto pt-5 inline-flex items-center text-sm font-bold text-[#085C84] underline decoration-[#2F9B3E] decoration-2 underline-offset-4">View description and download <ExternalLink className="ml-2 h-4 w-4" aria-hidden="true" /></span></Link>;
}

function ResourceSection({ title, items }: { title: string; items: LiteratureManifestItem[] }) {
  return <section className="mt-16 sm:mt-20"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow text-[#085C84]">Uploaded South Africa collection</p><h2 className="mt-3 font-serif text-3xl leading-tight tracking-[-0.035em] text-[#54595F] sm:text-4xl">{title}</h2></div><p className="text-sm text-[#7A7A7A]">{items.length} downloadable PDFs</p></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map(item => <ResourceCard key={item.slug} item={item} />)}</div></section>;
}

export default function LiteraturePage() {
  return <PublicLayout><main data-literature-deployment={literatureDeployment}>
    <section className="relative isolate overflow-hidden border-b border-[#DDE6EB] bg-[#EAF3F7] py-16 sm:py-24"><div className="pointer-events-none absolute -right-16 -top-20 h-72 w-72 rounded-full bg-[#387CBB]/15 blur-3xl" aria-hidden="true" /><div className="pointer-events-none absolute bottom-0 right-[19%] h-36 w-36 rounded-full border-[22px] border-[#2F9B3E]/10" aria-hidden="true" /><div className="site-container relative"><div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-[#085C84] text-white shadow-[0_12px_28px_rgba(8,92,132,0.18)]"><Library className="h-6 w-6" aria-hidden="true" /></div><p className="eyebrow mt-7 text-[#085C84]">NA Literature</p><h1 className="mt-4 max-w-4xl font-serif text-4xl leading-[1.04] tracking-[-0.04em] text-[#54595F] sm:text-6xl">The South Africa literature library, linked to the actual PDFs.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#54595F] sm:text-xl">Every item below comes from the supplied literature folder. Open a card for a short description and an exact PDF download. Detail pages open in a new tab so you can keep this catalogue available.</p></div></section>
    <section className="site-container py-14 sm:py-20"><div className="rounded-3xl border border-[#C7DFD1] bg-[#F2FAF4] p-6 sm:p-8"><div className="flex gap-4"><Download className="mt-1 h-6 w-6 shrink-0 text-[#20752C]" aria-hidden="true" /><div><h2 className="font-serif text-2xl text-[#54595F]">Each card leads to a real downloadable file.</h2><p className="mt-3 max-w-4xl leading-7 text-[#54595F]">The library uses the supplied PDF files uploaded to managed storage. Select any resource to open its description page in a new tab, then read the PDF or download it directly.</p><a href={officialCatalogue} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center font-bold text-[#085C84] underline decoration-[#2F9B3E] decoration-2 underline-offset-4">Compare with the official NA literature catalogue <ExternalLink className="ml-2 h-4 w-4" aria-hidden="true" /></a></div></div></div><div className="mt-10 flex items-center gap-3 text-sm font-semibold text-[#54595F]"><BookOpen className="h-5 w-5 text-[#085C84]" aria-hidden="true" />{literatureManifest.length} uploaded PDF resources mapped to exact download targets.</div>{categoryOrder.filter(category => grouped[category]?.length).map(category => <ResourceSection key={category} title={category} items={grouped[category]} />)}<section className="mt-16 rounded-3xl bg-[#085C84] p-7 text-white sm:p-10"><FileText className="h-7 w-7 text-[#B9E39E]" aria-hidden="true" /><h2 className="mt-6 font-serif text-3xl leading-tight">Need a different language or edition?</h2><p className="mt-4 max-w-2xl leading-7 text-white/90">The uploaded South Africa collection is available here for direct download. For other languages, editions, or printed copies, use the official NA World Services catalogue.</p><a href={officialCatalogue} target="_blank" rel="noreferrer" className="mt-7 inline-flex min-h-12 items-center rounded-xl bg-[#2F9B3E] px-5 py-3 font-bold text-white hover:bg-[#20752C]">Visit official catalogue <ExternalLink className="ml-2 h-4 w-4" /></a></section></section>
  </main></PublicLayout>;
}
