import { ArrowLeft, Download, ExternalLink, FileText } from "lucide-react";
import { Link } from "wouter";
import PublicLayout from "@/components/PublicLayout";
import { literatureManifest } from "@/data/literatureManifest";

export default function LiteratureDetail({ slug }: { slug: string }) {
  const item = literatureManifest.find(entry => entry.slug === slug);

  if (!item) {
    return <PublicLayout><main className="site-container py-24"><p className="eyebrow text-[#085C84]">Literature</p><h1 className="mt-4 font-serif text-4xl text-[#54595F]">Resource not found</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-[#54595F]">This literature item is not in the current uploaded catalogue.</p><Link href="/literature" className="mt-8 inline-flex items-center font-bold text-[#085C84] underline decoration-[#2F9B3E] decoration-2 underline-offset-4"><ArrowLeft className="mr-2 h-4 w-4" /> Back to Literature</Link></main></PublicLayout>;
  }

  return <PublicLayout><main>
    <section className="relative isolate overflow-hidden border-b border-[#DDE6EB] bg-[#EAF3F7] py-16 sm:py-24"><div className="pointer-events-none absolute -right-16 -top-20 h-72 w-72 rounded-full bg-[#387CBB]/15 blur-3xl" aria-hidden="true" /><div className="pointer-events-none absolute bottom-0 right-[19%] h-36 w-36 rounded-full border-[22px] border-[#2F9B3E]/10" aria-hidden="true" /><div className="site-container relative"><Link href="/literature" className="inline-flex items-center font-bold text-[#085C84] underline decoration-[#2F9B3E] decoration-2 underline-offset-4"><ArrowLeft className="mr-2 h-4 w-4" /> All literature</Link><div className="mt-12 inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-[#085C84] text-white shadow-[0_12px_28px_rgba(8,92,132,0.18)]"><FileText className="h-7 w-7" aria-hidden="true" /></div><p className="eyebrow mt-7 text-[#085C84]">{item.category}</p><h1 className="mt-4 max-w-4xl font-serif text-4xl leading-[1.04] tracking-[-0.04em] text-[#54595F] sm:text-6xl">{item.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#54595F] sm:text-xl">{item.description}</p></div></section>
    <section className="site-container grid gap-8 py-14 lg:grid-cols-[minmax(0,1fr)_360px] sm:py-20"><article className="rounded-3xl border border-[#DDE6EB] bg-white p-7 shadow-[0_12px_30px_rgba(20,45,42,0.05)] sm:p-10"><p className="eyebrow text-[#085C84]">About this file</p><h2 className="mt-3 font-serif text-3xl text-[#54595F]">A practical NA resource</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-[#54595F]">This item is part of the South Africa Region’s uploaded literature collection. Open the PDF to read it in a new tab, or use the download button to save a copy for offline reading.</p><dl className="mt-8 grid gap-4 border-t border-[#DDE6EB] pt-7 sm:grid-cols-2"><div><dt className="text-xs font-bold uppercase tracking-[0.14em] text-[#7A7A7A]">Category</dt><dd className="mt-2 font-semibold text-[#54595F]">{item.category}</dd></div><div><dt className="text-xs font-bold uppercase tracking-[0.14em] text-[#7A7A7A]">File</dt><dd className="mt-2 break-words font-semibold text-[#54595F]">{item.fileName}</dd></div></dl></article><aside className="h-fit rounded-3xl bg-[#085C84] p-7 text-white shadow-[0_16px_34px_rgba(8,92,132,0.16)] sm:p-8"><Download className="h-7 w-7 text-[#B9E39E]" aria-hidden="true" /><h2 className="mt-5 font-serif text-3xl">Read or download</h2><p className="mt-4 leading-7 text-white/90">The supplied PDF opens in a new browser tab. Use the download action if you want to keep a local copy.</p><a href={item.downloadUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-[#2F9B3E] px-5 py-3 font-bold text-white hover:bg-[#20752C]" download={item.fileName}><Download className="mr-2 h-4 w-4" /> Download PDF</a><a href={item.downloadUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center text-sm font-bold text-white underline decoration-[#B9E39E] decoration-2 underline-offset-4">Open PDF in a new tab <ExternalLink className="ml-2 h-4 w-4" /></a></aside></section>
  </main></PublicLayout>;
}
